/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const DiscountType = IDL.Variant({
  'fixed' : IDL.Null,
  'percentage' : IDL.Null,
});
export const Coupon = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiresAt' : IDL.Opt(IDL.Int),
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'minOrderValue' : IDL.Opt(IDL.Nat),
  'isActive' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'price' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Int,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
});
export const Review = IDL.Record({
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'applyCoupon' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat, IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCouponByCode' : IDL.Func([IDL.Text], [Coupon], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getReviewsForProduct' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProductInStock' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCoupon' : IDL.Func([IDL.Text], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCouponStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateOrderPaymentStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus],
      [PaymentStatus],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [OrderStatus], []),
  'upsertCoupon' : IDL.Func([Coupon], [IDL.Text], []),
  'upsertProduct' : IDL.Func([Product], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const DiscountType = IDL.Variant({
    'fixed' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const Coupon = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiresAt' : IDL.Opt(IDL.Int),
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'minOrderValue' : IDL.Opt(IDL.Nat),
    'isActive' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'price' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Int,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentStatus' : PaymentStatus,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
  });
  const Review = IDL.Record({
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'applyCoupon' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat, IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCouponByCode' : IDL.Func([IDL.Text], [Coupon], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getNewArrivals' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getReviewsForProduct' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProductInStock' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCoupon' : IDL.Func([IDL.Text], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCouponStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateOrderPaymentStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus],
        [PaymentStatus],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [OrderStatus], []),
    'upsertCoupon' : IDL.Func([Coupon], [IDL.Text], []),
    'upsertProduct' : IDL.Func([Product], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };