/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Coupon {
  'discountValue' : bigint,
  'expiresAt' : [] | [bigint],
  'code' : string,
  'discountType' : DiscountType,
  'minOrderValue' : [] | [bigint],
  'isActive' : boolean,
}
export type DiscountType = { 'fixed' : null } |
  { 'percentage' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'stripePaymentIntentId' : [] | [string],
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'isNewArrival' : boolean,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'price' : bigint,
  'isBestSeller' : boolean,
}
export interface Review {
  'userId' : Principal,
  'createdAt' : bigint,
  'productId' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'applyCoupon' : ActorMethod<[string, bigint], [bigint, bigint]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[[] | [string]], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getActiveCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBestSellers' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCouponByCode' : ActorMethod<[string], Coupon>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getNewArrivals' : ActorMethod<[], Array<Product>>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getReviewsForProduct' : ActorMethod<[bigint], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProductInStock' : ActorMethod<[bigint], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeCoupon' : ActorMethod<[string], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCouponStatus' : ActorMethod<[string, boolean], undefined>,
  'updateOrderPaymentStatus' : ActorMethod<
    [bigint, PaymentStatus],
    PaymentStatus
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], OrderStatus>,
  'upsertCoupon' : ActorMethod<[Coupon], string>,
  'upsertProduct' : ActorMethod<[Product], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];